apiVersion: v1
kind: Service
metadata:
  name: base-layouts-staging
  namespace: webresto
spec:
  ports:
  - name: http
    port: 7080
    targetPort: 7080
  selector:
    app: base-layouts-staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-layouts-staging
  namespace: webresto
spec:
  selector:
    matchLabels:
      app: base-layouts-staging
  replicas: 1
  template:
    metadata:
      labels:
        app: base-layouts-staging
    spec:
      containers:
      - name: base-layouts-staging
        image: git.hm:5050/webresto/factory/layout_docker_images:base
        imagePullPolicy: Always
        ports:
        - containerPort: 7080
        env:
        - name: WS_ADDRESS
          value: "wss://base-layouts.webresto.dev/ws"
        - name: PREVIEW_ADDRESS
          value: "https://base-layouts.webresto.dev/preview"
        - name: TG_APIKEY
          value: "<TG_APIKEY>"        
        - name: TG_CHAT_ID
          value: "<TG_CHAT_ID>"                    
        - name: REVISION
          value: "<REVISION>"
        - name: DEPLOY_TOKEN_42PUB
          value: "<DEPLOY_TOKEN_42PUB>"
      imagePullSecrets:
      - name: regcred-webresto

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: base-layouts-staging-ingress
  namespace: webresto
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/server-snippet: |
        gzip on;
        gzip_disable "MSIE [1-6]\.";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 1;
        gzip_min_length 512;
        gzip_buffers 16 128k;
        gzip_http_version 1.1;
        gzip_types
            application/json
            application/vnd.api+json;    
spec:
  tls:
  - hosts:
    - base-layouts.webresto.dev
    secretName: base-layouts-staging-tls
  rules:
  - host: base-layouts.webresto.dev
    http:
      paths:
      - backend:
          serviceName: base-layouts-staging
          servicePort: 7080